{{- $name := include "shoppingweb.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "shoppingweb.name" . }}
    chart: {{ template "shoppingweb.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ApiSettings__GatewayAddress: http://yarpgateway:8010
