{{- $name := include "basketapi.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "basketapi.name" . }}
    chart: {{ template "basketapi.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ConnectionStrings__Database: Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
  ConnectionStrings__Redis: distributedcache:6379
  GrpcSettings__DiscountUrl: http://discountgrpc:8003
  MessageBroker__Host: amqp://ecommerce-mq:5672
  MessageBroker__UserName: guest
  MessageBroker__Password: guest
  ElasticConfiguration__Uri: http://elasticsearch:9200