apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributed-cache
  template:
    metadata:
      labels:
        app: distributed-cache
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: distributedcache
spec:
  selector:
    app: distributed-cache
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
