apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - name: http
          protocol: TCP
          containerPort: 15672
        - name: amqp
          protocol: TCP
          containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        #restartPolicy: Always
# spec:
#     app: message-broker
#   ports:
#   - name: rabbitmq
#     port: 5672
#     targetPort: 5672
#   - name: rabbitmq-management
#     port: 15672
#     targetPort: 15672
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq
# spec:
#   selector:
#     app: rabbitmq
#   ports:
#   - name: http
#     protocol: TCP
#     port: 15672
#     targetPort: 15672
#   - name: prometheus
#     protocol: TCP
#     port: 15692
#     targetPort: 15692
#   - name: amqp
#     protocol: TCP
#     port: 5672
#     targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-mq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: rabbitmq-management
    protocol: TCP
    port: 15672
    targetPort: 15672
