apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - name: basket-api
        image: sharadit/basketapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ConnectionStrings__Database
          # - name: ASPNETCORE_HTTPS_PORTS
          #   value: "/https/aspnetapp.pfx"
          # - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          #   value: "Sharad@1"
          # - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          #   value: "8081"
          value: "Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true"
        - name: ConnectionStrings__Redis
          value: "distributedcache:6379"
        - name: GrpcSettings__DiscountUrl
          value: "http://discount-grpc:8003"
        - name: MessageBroker__Host
          value: "amqp://ecommerce-mq:5672"
        - name: MessageBroker__UserName
          value: "guest"
        - name: MessageBroker__Password
          value: "guest"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: basket-api
spec:
  type: NodePort
  selector:
    app: basket-api
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8080
    nodePort: 31001
