apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: sharadit/catalogapi:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ConnectionStrings__Database
          # - name: ASPNETCORE_HTTPS_PORTS
          #   value: "/https/aspnetapp.pfx"
          # - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          #   value: "Sharad@1"
          # - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          #   value: "8081"
          value: "Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true"

        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
        #- containerPort: 8081
      #   volumeMounts:
      #   - name: aspnet-https
      #     mountPath: /https
      #     readOnly: true
      # volumes:
      # - name: aspnet-https
      #   hostPath:
      #     path: /home/user/.aspnet/https

# metadata:
---
#   name: catalog-api
# spec:
#   selector:
#     app: catalog-api
#   ports:
#   - name: http
#     protocol: TCP
#     port: 7000
#     targetPort: 8080
#   type: ClusterIP
# - name: https
#   protocol: TCP
#   port: 8081
#   targetPort: 8081
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  type: NodePort
  selector:
    app: catalog-api
  ports:
  - port: 8000
    targetPort: 8080
    nodePort: 31000
