apiVersion: v1
kind: Service
metadata:
  name: {{ include "messagebroker.fullname" . }}
  labels:
    {{- include "messagebroker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      protocol: TCP
      port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpTargetPort }}
    - name: rabbitmq-management
      protocol: TCP
      port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementTargetPort }}
  # ports:
  #   - port: {{ .Values.service.port }}
  #     targetPort: http
  #     protocol: TCP
  #     name: http
  selector:
    {{- include "messagebroker.selectorLabels" . | nindent 4 }}

# service:
#   type: ClusterIP
#   amqpPort: 5672
#   managementPort: 15672
#   selector:
#     app: rabbitmq
  # ports:
  #   - name: amqp
  #     protocol: TCP
  #     port: 5672
  #     targetPort: 5672
  #   - name: rabbitmq-management
  #     protocol: TCP
  #     port: 15672
  #     targetPort: 15672